version: '3'
services:
  apache:
    container_name: apache
    restart: always
    image: mostutw/lap
    volumes:
     - ./code:/var/www/html
     - ./apache/conf:/etc/apache2/sites-available
     - ./apache/log:/var/log/apache2
     - ./apache/ssl:/etc/ssl/import
     - ./mnt:/mnt
    ports:
     - 80:80
     - 443:443
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7.33
    environment:
      - "MYSQL_ROOT_PASSWORD=pass"
      - "MYSQL_DATABASE=test"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mnt:/mnt
    ports:
      - 3306:3306
    command: mysqld  --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

  mssql:
    container_name: mssql
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - "ACCEPT_EULA=Y"
     - "SA_PASSWORD=P@ssw0rd"
    volumes:
     - ./mnt:/mnt
    ports:
      - 1433:1433
volumes:
  mysql_volume:
